
export const addMedicineConstants = {
  SET_FORM: 'ADDMEDICINE_SET_FORM',
  SET_NAME: 'ADDMEDICINE_SET_NAME',
  SET_STRENGTH: 'ADDMEDICINE_SET_STRENGTH',
  SET_FREQUENCY: 'ADDMEDICINE_SET_FREQUENCY',
  SET_REMARK: 'ADDMEDICINE_SET_REMARK',
  SET_SUBMITTED: 'ADDMEDICINE_SET_SUBMITTED',
  LOGOUT: 'ADDMEDICINE_LOGOUT_REQUEST'
};
