export const authenticationConstants = {
  LOGIN_REQUEST: 'LOGINFORM_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGINFORM_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGINFORM_LOGIN_FAILURE',
  LOGOUT: 'LOGINFORM_LOGOUT'
};
