
export const constants = {
  SETTINGS_DEFAULT_PRINTERS: 'SETTINGS_DEFAULT_PRINTERS',
  SETTINGS_DEFAULT_PRINTER_BACKGROUND_PRINT: 'SETTINGS_DEFAULT_PRINTER_BACKGROUND_PRINT',

  SETTINGS_SAVE_REQUEST:'SETTINGS_SAVE_REQUEST',
  SETTINGS_SAVE_SUCCESS: 'SETTINGS_SAVE_SUCCESS',
  SETTINGS_SAVE_FAILURE: 'SETTINGS_SAVE_FAILURE',

  SETTINGS_FETCH_REQUEST:'SETTINGS_FETCH_REQUEST',
  SETTINGS_FETCH_SUCCESS: 'SETTINGS_FETCH_SUCCESS',
  SETTINGS_FETCH_FAILURE: 'SETTINGS_FETCH_FAILURE'
};
