
export const constants = {
  SYSTEM_PRINTERS: 'SYSTEM_PRINTERS',
  SYSTEM_DEFAULT_PRINTERS: 'SYSTEM_DEFAULT_PRINTERS',
  SYSTEM_DEFAULT_PRINTER_BACKGROUND_PRINT: 'SYSTEM_DEFAULT_PRINTER_BACKGROUND_PRINT'
};
