
export const constants = {
  SET_PRODUCT_NAME: 'SET_PRODUCT_NAME',
  SET_TYPE: 'SET_TYPE',
  SET_STRENGTH: 'SET_STRENGTH',
  SET_GENRIC: 'SET_GENRIC',
  SET_INDICATION: 'SET_INDICATION',
  SET_SUBMITTED: 'SET_SUBMITTED',
  SAVE_MEDICINE_REQUEST: 'SAVE_MEDICINE_REQUEST',
  SAVE_MEDICINE_SUCCESS: 'SAVE_MEDICINE_SUCCESS',
  RESET_MEDICINE_STATE: 'RESET_MEDICINE_STATE',
  FETCH_MEDICINE_REQUEST: 'FETCH_MEDICINE_REQUEST',
  FETCH_MEDICINE_SUCCESS: 'FETCH_MEDICINE_SUCCESS',
  FETCH_MEDICINE_FAILURE:  'FETCH_MEDICINE_FAILURE'
};
