
export const constants = {
  SET_FORM: 'ADDMEDICINE_SET_FORM',
  SET_NAME: 'ADDMEDICINE_SET_NAME',
  SET_STRENGTH: 'ADDMEDICINE_SET_STRENGTH',
  SET_FREQUENCY: 'ADDMEDICINE_SET_FREQUENCY',
  SET_REMARK: 'ADDMEDICINE_SET_REMARK',
  SET_SUBMITTED: 'ADDMEDICINE_SET_SUBMITTED',
  SAVE_MEDICINE_SUCCESS: 'NEW_MEDICINE_ADDED',
  FETCH_MEDICINE_REQUEST: 'FETCH_MEDICINE_REQUEST',
  FETCH_MEDICINE_SUCCESS: 'FETCH_MEDICINE_SUCCESS',
  FETCH_MEDICINE_FAILURE:  'FETCH_MEDICINE_FAILURE'
};
