
export const constants = {
  SET_PATIENT_NAME: 'SET_PATIENT_NAME',
  SET_PATIENT_AGE: 'SET_PATIENT_AGE',
  SET_PATIENT_SEX: 'SET_PATIENT_SEX',
  SET_PATIENT_MOBILE: 'SET_PATIENT_MOBILE',
  SET_PATIENT_EMAIL: 'SET_PATIENT_EMAIL',
  SET_PATIENT_PATIENTID: 'SET_PATIENT_PATIENTID',

  SET_PATIENT_MEDICINE: 'SET_PATIENT_MEDICINE',
  SET_PATIENT_OE: 'SET_PATIENT_OE',
  SET_PATIENT_CC: 'SET_PATIENT_CC',
  SET_PATIENT_TESTS: 'SET_PATIENT_TESTS',
  SET_PATIENT_ADVICE: 'SET_PATIENT_ADVICE',
  SET_PATIENT_FOLLOWUPDATE: 'SET_PATIENT_FOLLOWUPDATE',


  PATIENT_SAVE_REQUEST:'PATIENT_SAVE_REQUEST',
  PATIENT_SAVE_SUCCESS: 'PATIENT_SAVE_SUCCESS',
  PATIENT_SAVE_FAILURE: 'PATIENT_SAVE_FAILURE',

  PATIENT_FETCH_REQUEST:'PATIENT_FETCH_REQUEST',
  PATIENT_FETCH_SUCCESS: 'PATIENT_FETCH_SUCCESS',
  PATIENT_FETCH_FAILURE: 'PATIENT_FETCH_FAILURE'
};
